# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvjd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('job_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cv',
            name='description',
        ),
        migrations.AddField(
            model_name='cv',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='text_from_doc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='document',
            field=models.FileField(upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvjd.CV'),
        ),
    ]
