# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvjd', '0003_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='cvjd.Candidate'),
        ),
        migrations.AlterField(
            model_name='match',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='cvjd.Job'),
        ),
    ]
