# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvjd', '0006_auto_20190408_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
