# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvjd', '0007_match_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
