# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvjd', '0008_match_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
