# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvjd', '0009_match_current_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='cvjd.Candidate'),
        ),
        migrations.AlterField(
            model_name='match',
            name='current_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_job', to='cvjd.Job'),
        ),
        migrations.AlterField(
            model_name='match',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='cvjd.Job'),
        ),
    ]
