# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvjd', '0010_auto_20190514_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='drive_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
